#!/usr/bin/env python
# -*- coding: utf-8 -*-

import math
import sys

print('#mesh version 0.01')
print('#auto-generated by', sys.argv[0])

divs = int(sys.argv[1]) if len(sys.argv) > 1 else 4
hastopbot = sys.argv[2] == "yes" if len(sys.argv) > 2 else True
print('\n\n#vertices')
for i in range(0, divs):
    dph = math.pi / divs
    phi = i * 2 * dph
    so, co = math.sin(phi), math.cos(phi)
    s1, c1 = math.sin(phi - dph), math.cos(phi - dph)
    s2, c2 = math.sin(phi + dph), math.cos(phi + dph)
    #     Position                  Normal       TexCoords
    print(0.5 * s2, 0.5 * c2,  0.5, so, co, 0.0, 1.0, 1.0)
    print(0.5 * s1, 0.5 * c1,  0.5, so, co, 0.0, 0.0, 1.0)
    print(0.5 * s2, 0.5 * c2, -0.5, so, co, 0.0, 1.0, 0.0)
    print(0.5 * s2, 0.5 * c2, -0.5, so, co, 0.0, 1.0, 0.0)
    print(0.5 * s1, 0.5 * c1,  0.5, so, co, 0.0, 0.0, 1.0)
    print(0.5 * s1, 0.5 * c1, -0.5, so, co, 0.0, 0.0, 0.0)
    print('\n')
    if hastopbot:
        #     Position                  Normal         TexCoords
        print(0.5 * s1, 0.5 * c1,  0.5, 0.0, 0.0,  1.0, 0.0, 0.0)
        print(0.5 * s2, 0.5 * c2,  0.5, 0.0, 0.0,  1.0, 1.0, 0.0)
        print(0.0,      0.0,       0.5, 0.0, 0.0,  1.0, 1.0, 1.0)
        print(0.5 * s1, 0.5 * c1, -0.5, 0.0, 0.0, -1.0, 0.0, 0.0)
        print(0.5 * s2, 0.5 * c2, -0.5, 0.0, 0.0, -1.0, 1.0, 0.0)
        print(0.0,      0.0,      -0.5, 0.0, 0.0, -1.0, 1.0, 1.0)
        print('\n')

print('\n\n#indices')
eachverts = 12 if hastopbot else 6
for i in range(divs * eachverts):
    print(i)


'''
-0.5 -0.5  0.5  0.0  0.0  1.0   0.0 0.0
 0.5 -0.5  0.5  0.0  0.0  1.0   1.0 0.0
 0.5  0.5  0.5  0.0  0.0  1.0   1.0 1.0
 0.5  0.5  0.5  0.0  0.0  1.0   1.0 1.0
-0.5  0.5  0.5  0.0  0.0  1.0   0.0 1.0
-0.5 -0.5  0.5  0.0  0.0  1.0   0.0 0.0
'''
